// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/lamxy/fiberhouse"
	"github.com/lamxy/fiberhouse/example_application/module/example-module/model"
	"github.com/lamxy/fiberhouse/example_application/module/example-module/repository"
	"github.com/lamxy/fiberhouse/example_application/module/example-module/service"
)

// Injectors from api_provider.go:

func InjectExampleApi(ctx fiberhouse.IApplicationContext) (*ExampleHandler, error) {
	exampleModel := model.NewExampleModel(ctx)
	exampleRepository := repository.NewExampleRepository(ctx, exampleModel)
	exampleService := service.NewExampleService(ctx, exampleRepository)
	exampleHandler := NewExampleHandler(ctx, exampleService)
	return exampleHandler, nil
}
